//
//  ViewTwoPresenter.swift
//  ViperDemo
//
//  Created by Tomislav Luketic on 9/22/19.
//  Copyright (c) 2019 lux. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ViewTwoPresenter {

    // MARK: - Private properties -

    private unowned let view: ViewTwoViewInterface
    private let interactor: ViewTwoInteractorInterface
    private let wireframe: ViewTwoWireframeInterface

    // MARK: - Lifecycle -

    init(view: ViewTwoViewInterface, interactor: ViewTwoInteractorInterface, wireframe: ViewTwoWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension ViewTwoPresenter: ViewTwoPresenterInterface {
    func didTapCloseButton() {
        self.wireframe.dismiss(animated: true)
    }
    
}
