//
//  ViewTwoViewController.swift
//  ViperDemo
//
//  Created by Tomislav Luketic on 9/22/19.
//  Copyright (c) 2019 lux. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ViewTwoViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: ViewTwoPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }
    @IBAction func closeButtonTapped(_ sender: Any) {
        presenter.didTapCloseButton()
    }
    
}

// MARK: - Extensions -

extension ViewTwoViewController: ViewTwoViewInterface {
}
