//
//  ViewTwoInterfaces.swift
//  ViperDemo
//
//  Created by Tomislav Luketic on 9/22/19.
//  Copyright (c) 2019 lux. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ViewTwoWireframeInterface: WireframeInterface {
}

protocol ViewTwoViewInterface: ViewInterface {
}

protocol ViewTwoPresenterInterface: PresenterInterface {
    func didTapCloseButton()
}

protocol ViewTwoInteractorInterface: InteractorInterface {
}
