//
//  ViewOneInterfaces.swift
//  ViperDemo
//
//  Created by Tomislav Luketic on 9/22/19.
//  Copyright (c) 2019 lux. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ViewOneWireframeInterface: WireframeInterface {
}

protocol ViewOneViewInterface: ViewInterface {
}

protocol ViewOnePresenterInterface: PresenterInterface {
}

protocol ViewOneInteractorInterface: InteractorInterface {
}
