//
//  ViewOneViewController.swift
//  ViperDemo
//
//  Created by Tomislav Luketic on 9/22/19.
//  Copyright (c) 2019 lux. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ViewOneViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: ViewOnePresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }
	
}

// MARK: - Extensions -

extension ViewOneViewController: ViewOneViewInterface {
}
