//
//  ViewOnePresenter.swift
//  ViperDemo
//
//  Created by Tomislav Luketic on 9/22/19.
//  Copyright (c) 2019 lux. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ViewOnePresenter {

    // MARK: - Private properties -

    private unowned let view: ViewOneViewInterface
    private let interactor: ViewOneInteractorInterface
    private let wireframe: ViewOneWireframeInterface

    // MARK: - Lifecycle -

    init(view: ViewOneViewInterface, interactor: ViewOneInteractorInterface, wireframe: ViewOneWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension ViewOnePresenter: ViewOnePresenterInterface {
}
