//
//  ViewOneInteractor.swift
//  ViperDemo
//
//  Created by Tomislav Luketic on 9/22/19.
//  Copyright (c) 2019 lux. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ViewOneInteractor {
}

// MARK: - Extensions -

extension ViewOneInteractor: ViewOneInteractorInterface {
}
