//
//  HomeInterfaces.swift
//  ViperDemo
//
//  Created by Tomislav Luketic on 9/22/19.
//  Copyright (c) 2019 lux. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum HomeNavigationOption {
    case ViewOne
    case ViewTwo
}

protocol HomeWireframeInterface: WireframeInterface {
   func navigate(to option: HomeNavigationOption)
}

protocol HomeViewInterface: ViewInterface {
}

protocol HomePresenterInterface: PresenterInterface {
    func didTapViewOneButton()
    func didTapViewTwoButton()
}

protocol HomeInteractorInterface: InteractorInterface {
}
