//
//  HomeViewController.swift
//  ViperDemo
//
//  Created by Tomislav Luketic on 9/22/19.
//  Copyright (c) 2019 lux. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HomeViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: HomePresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        self.title = "Home"
    }
    @IBAction func viewOneButtonTapped(_ sender: Any) {
        presenter.didTapViewOneButton()
    }
    @IBAction func viewTwoButtonTapped(_ sender: Any) {
        presenter.didTapViewTwoButton()
    }
    
}

// MARK: - Extensions -

extension HomeViewController: HomeViewInterface {
}
